plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nn.launcher'
    compileSdk 34

    defaultConfig {
        applicationId "com.nn.launcher"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
